name: yellow_box
description: source of your creativity

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3
  fluttertoast: ^8.0.9
  sqflite: ^2.0.2
  speech_to_text: ^5.4.3
  shared_preferences: ^2.0.13
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
